### ISSUE TITLE
FORMAT crashes with division by zero on a 2 TiB FAT-32 partition

### ISSUE THREAD

**Issue by boeckmann** [FDOS/format#1]
Wilhelm Spiegl reported that FROMAT crashes with a divison by zero error when trying a 2 TiB FAT-32 partition. I could reproduce the problem. The determination of the FAT size and/or its start-end sectors seem to fail. See attached screenshots.

![Format_Error_1](https://github.com/FDOS/format/assets/6333969/921bcb5c-3d97-40bd-b12a-8ece13f4f6b7)
![Format_Error_2](https://github.com/FDOS/format/assets/6333969/f7b1aa2e-7021-4f72-a269-28efe46417da)

**Comment by boeckmann** [comment]
I could track down the error to the FreeDOS **kernel function 440D,4860**. This functions **returns a zero in the DWORD logical_sectors_per_fat** (see fat_size_high and fat_size_low in screenshot), while setting no error flag. FORMAT therefore accepts the fat size returned by the Kernel and works with the non-valid value, eventually leading to the division by zero.

![INT_21,440D,4860_2TiB_partition](https://github.com/FDOS/format/assets/6333969/47bb27e6-b4bb-48a7-996c-158bf48f165b)

**Comment by boeckmann** [comment]
It should be mentioned that the number of logical fat sectors is returned correctly by INT21 function 440d,4860 if the partition is slightly smaller than 2 TiB.

**Comment by PerditionC** [comment]
kernel bug?

**Comment by boeckmann** [comment]
Maybe. A candidate for an integer wrap-around is:

- https://github.com/FDOS/kernel/blob/95694f7e349f6a7b433292448bd0890b10657214/kernel/initdisk.c#L485C50-L485C50

There is a DebugPrintf a few lines later. If this spits out `fatlen=0` on the 2 TiB partition, we know for sure.

**Comment by boeckmann** [comment]
@PerditionC if you are short on time I can try to figure it out by myself, and provide a patch in case of an error. But it will probably take me a week or so.

**Comment by andrewbird** [comment]
I thought I'd write a test for dosemu's test suite for this, but I seem to be running into a limitation. I created a sparse file of 3 TiB to use as a pseudo disk, then as a check ran Linux's FDISK on it. However I get this response.
~~~
 ajb@calypso:/clients/common/dosemu2.git$ ls -lh /tmp/devbpbi.tst
-rw-r--r-- 1 ajb sphere 3.0T Nov 29 12:26 /tmp/devbpbi.tst

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognised partition table.
The size of this disk is 3 TiB (3298534883328 bytes). DOS partition table format
cannot be used on drives for volumes larger than 2199023255040 bytes for 512-byte sectors.
Use GUID partition table format (GPT).

Created a new DOS disklabel with disk identifier 0xb1182dbe.

Command (m for help): p
Disk /tmp/devbpbi.tst: 3 TiB, 3298534883328 bytes, 6442450944 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xb1182dbe

Command (m for help): 
~~~

So my question is, is the only fix possible that the kernel returns an error if the disk is 2TiB or larger, or else non 512B sectors would need to be supported?

**Comment by boeckmann** [comment]
> So my question is, is the only fix possible that the kernel returns an error if the disk is 2TiB or larger, or else non 512B sectors would need to be supported?

@andrewbird I don't think the kernel has to throw an error on such disks. Creating and using a 2TiB MBR partition even on a 3TiB disk should be perfectly fine. One pitfall is that the 32-bit sector variables may overflow on disks >2TiB. Free FDISK therefore restricts the disk size returned by the BIOS to 2TiB. This is done here: https://github.com/FDOS/fdisk/blob/b3ef4505e38c78978788555a1e8b4da91578aead/source/fdisk/pdiskio.c#L562

There is also another option: implement GPT support in initdisk.c. This should actually be easier than updating the Kernel to support non-512-byte sectors, I think. To my knowledge, Tom Ehlert already did some work on GPT support. But for reasons unknown to me it did not land in the official kernel.

**Comment by boeckmann** [comment]
But to make use of GPT partition >2TiB the variables storing the sector numbers had to be adjusted to 64-bit.

**Comment by PerditionC** [comment]
GPT support is being worked on, I have it partially working with Open Watcom but haven't had a chance to figure out the math helpers for GCC for 64bit math.  Tom's code was merged with my work, but it is limited to finding DOS partitions and requires they still be within 32 bit limits.   I'm working on 64 bit GPT support.  As such, only 386+ built kernels will offer GPT support (at least until a 8086 version of math helpers get written)

**Comment by PerditionC** [comment]
cool, I will look at this more this evening.  VirtualBox does not handle 2TB fake drives so well: its BIOS anyway.  my test drive fdisks fine at 2TB but is 0 bytes on reboot so can't try format.  It took me some trial and error to find a disk size close to 2TB that didn't wrap due to overflow since fdisk would only see size % 2TB drive.  Haven't yet determined if this is a related kernel bug or VirtualBox issue.

**Comment by boeckmann** [comment]
@PerditionC did you use a recent FDISK or 1.3.4? If it is 1.3.4, please try it again with 1.3.11. Otherwise this may also be an FDISK related bug.

Regarding VirtualBox, depending on version, OS and disk image type (VDI, VHD etc.) I also experienced strange behaviour. For me, the following combo works: VirtualBox 7.0.12 on Win11, 2 TB VDI disk. FDISK 1.3.11, kernel master.

**Comment by diekleineHexe** [comment]
> For clarification, it's not holding a 64bit value or adding 64bit values that invoke the helper function, its multiplication. Also, these are compiler helper functions, so invisible to the C code more or less - these are internal runtime functions that we have to provide substitutes for since not using the compiler's runtime.

where would you need 64bit multiplkation?

**Comment by andrewbird** [comment]
> @andrewbird I don't think the kernel has to throw an error on such disks. Creating and using a 2TiB MBR partition even on a 3TiB disk should be perfectly fine.

@boeckmann as you can probably tell I have no experience with using DOS or Windows on such large disks. I've been playing with FDPP making it work with those large disks / partitions. I wanted to exercise my changes, but I have no local disks that large so I'm using a sparse image file on Linux.  From the way I read the partition fields in the MBR (start LBA, size) I figured that I could create a 3TiB file with two partitions, the first from the start to 100MiB under 2TiB, then a second following it up to the full 3TiB. I would test this second partition under FDPP. However Linux fdisk won't let me do this, only the 100MiB remaining under 2 TiB is considered valid space to create the second partition. Is this a valid scheme? Would Windows and FreeDOS fdisk be able to do it?

Thanks, Andrew

**Comment by boeckmann** [comment]
Hi @andrewbird,

Free FDISK ist not able to create partitions that go beyond the 2 TiB barrier. This is because Free FDISK stores sector numbers as 32-bit unsigned, and only supports 512 byte sector size. This makes up for the 2 TiB.

MBR also stores starting sector and length as 32 bit unsigned.

There are (somewhat incompatible) tricks one can do. Given that a program stores sector numbers as 64-bit ints, one can access up to 4 TiB with the MBR partitioning scheme: Start just below 2 TiB and create a 2 TiB partition, like you intended with the 3 TiB disk. If sector size is increased, even larger disks / partitions are supported. So theoretically, with MBR you can handle drives larger 2 TiB. In practice, most tools can not.

Regarding recent Windows versions, I do not know exactly what the limits are. Would be interesting to find out. Would also be interesting to find out which combinations of OS / tool support such "extended" layouts :-)

**Comment by boeckmann** [comment]
Regarding the above formula transformation, I am now confident that this is ok. I tried to make a proof (sorry, for not properly type-setting it):

The problem is of the form
```
x = (a + b) div d
```
where `a + b` may overflow before integer division. Changing it to `x = a div d + b div d` would be wrong, because `div` rounds down.

One can re-write `a` as `a = (a div d) * d + r`, with `r = a mod d`. This leads to the following equivalent formulas:
```
x = (a + b) div d
  = ((a div d) * d + r + b) div d
  = (a div d) + (r + b) div d
```
So the formulas should be equivalent, apart from the overflow characteristics. I hope it is correct. Are mathematicians here?

**Comment by PerditionC** [comment]
suggested solution committed to kernel, in testing it works better and avoids the divide by 0 by format

**Comment by boeckmann** [comment]
Fixed by https://github.com/FDOS/kernel/commit/cfdd09963fa7bc473942fcc643586233e88c3d68.
